export const ADD_TO_FAVOURITES_START = 'ADD_TO_FAVOURITES_START';
export const ADD_TO_FAVOURITES_SUCCESS = 'ADD_TO_FAVOURITES_SUCCESS';
export const ADD_TO_FAVOURITES_FAIL = 'ADD_TO_FAVOURITES_FAIL';

export const REMOVE_FROM_FAVOURITES_START = 'REMOVE_FROM_FAVOURITES_START';
export const REMOVE_FROM_FAVOURITES_SUCCESS = 'REMOVE_FROM_FAVOUR_SUCCESSITES';
export const REMOVE_FROM_FAVOURITES_FAIL = 'REMOVE_FROM_FAVO_FAILURITES';

export const FETCH_FAVOURITES_START = 'FETCH_FAVOURITES_START';
export const FETCH_FAVOURITES_SUCCESS = 'FETCH_FAVOURITES_SUCCESS';
export const FETCH_FAVOURITES_FAIL = 'FETCH_FAVOURITES_FAIL';

export const AUTH_START = 'AUTH_STARTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';

export const FETCH_CURRENT_TIME_START = 'FETCH_CURRENT_TIME_START';
export const FETCH_CURRENT_TIME_SUCCESS = 'FETCH_CURRENT_TIME_SUCCESS';
export const FETCH_CURRENT_TIME_FAIL = 'FETCH_CURRENT_TIME_FAIL';